#	server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003

spring:
  application:
    name: product-data-service

  zipkin:
    enabled: true #是否启用
    #zipkin服务所在地址
    base-url: http://localhost:9411/
    sender:
      type: web #使用http的方式传输数据到, Zipkin请求量比较大，可以通过消息中间件来发送，比如 RabbitMQ
    #配置采样百分比
    sleuth:
      sampler:
        probability: 1 # 将采样比例设置为 1.0，也就是全部都需要。默认是0.1也就是10%，一般情况下，10%就够用了

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      设置注册中心的地址： http://localhost:8761/eureka/ , 与 eureka-server 中的配置 application.yml 遥相呼应
